-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 21:59:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wether
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wether
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wether` DEFAULT CHARACTER SET utf8 ;
USE `wether` ;

-- -----------------------------------------------------
-- Table `wether`.`openwether`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wether`.`openwether` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temperatur` VARCHAR(45) NOT NULL,
  `wind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `wind`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wether`.`tomorrowapi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wether`.`tomorrowapi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `temperatur` VARCHAR(45) NOT NULL,
  `wind` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `temperatur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wether`.`endData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wether`.`endData` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `windOpenWethte` VARCHAR(45) NOT NULL,
  `temperatureTomorrowapi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `openwether_idx` (`windOpenWethte` ASC) VISIBLE,
  INDEX `tomorrowapi_idx` (`temperatureTomorrowapi` ASC) VISIBLE,
  CONSTRAINT `openwether`
    FOREIGN KEY (`windOpenWethte`)
    REFERENCES `wether`.`openwether` (`wind`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tomorrowapi`
    FOREIGN KEY (`temperatureTomorrowapi`)
    REFERENCES `wether`.`tomorrowapi` (`temperatur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
